version: '3.8'

services:
  app:
    build: ./app
    container_name: vpn_app
    environment:
      - TELEGRAM_TOKEN=7697602760:AAEdu5NLl2UEZYTuyAit3ImiziiVn_vYppE
    volumes:
      - ./xray/config.json:/app/config.json
      - /var/run/docker.sock:/var/run/docker.sock
      - app_data:/app/data
    # Порт 8000 больше не нужно пробрасывать наружу
    networks:
      - vpn_net
    restart: always

  xray:
    image: teddysun/xray
    container_name: vpn_xray
    volumes:
      - ./xray/config.json:/etc/xray/config.json
    # Пробрасываем наружу порт 443, который будет слушать Xray
    ports:
      - "443:443"
    networks:
      - vpn_net
    restart: always

volumes:
  app_data:

networks:
  vpn_net:
    driver: bridge