version: '3.8'

services:
  app:
    build: ./app
    container_name: vpn_app
    environment:
      - TELEGRAM_TOKEN=7697602760:AAEdu5NLl2UEZYTuyAit3ImiziiVn_vYppE
      - VPN_PASSWORD=1234
      - VLESS_SERVER_ADDRESS=shieldvpn.ru
      - REALITY_PUBLIC_KEY=8PSiSpiSdXQLCGVXszWueRRsqflMboBXBFAx7MDLTjo
    volumes:
      # Папка для файла базы данных SQLite. Надежно и правильно.
      - ./app/database:/app/database
      # Общая папка, куда app будет генерировать конфиг для xray
      - ./shared_xray_config:/app/xray_config
      # Сокет Docker для управления контейнерами (чтобы перезапускать xray)
      - /var/run/docker.sock:/var/run/docker.sock
      # Порт 8000 не нужен, но оставим на будущее для вебхуков
    ports:
      - "8000:8000"
    networks:
      - vpn_net
    depends_on:
      - xray

  xray:
    image: teddysun/xray
    container_name: vpn_xray
    volumes:
      - ./shared_xray_config:/etc/xray
    ports:
      - "8443:8443"
    networks:
      vpn_net:
        aliases:
          - xray_alias

  caddy:
    image: caddy:2.7.6
    container_name: vpn_caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy:/etc/caddy
      - ./caddy:/srv/www
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - vpn_net
    depends_on:
      - xray
      - app

volumes:
  caddy_data:
  caddy_config:

networks:
  vpn_net:
    driver: bridge
