version: '3.8'

services:
  app:
    build: ./app
    container_name: vpn_app
    environment:
      - TELEGRAM_TOKEN=7697602760:AAEdu5NLl2UEZYTuyAit3ImiziiVn_vYppE
      - VPN_PASSWORD=1234
      - VLESS_SERVER_ADDRESS=shieldvpn.ru
      - REALITY_PUBLIC_KEY=8PSiSpiSdXQLCGVXszWueRRsqflMboBXBFAx7MDLTjo
    volumes:
      - ./shared_xray_config:/app/xray_config
      - ./app/database:/app/database
    ports:
      - "8000:8000"  # для API
    networks:
      - vpn_net

  xray:
    image: teddysun/xray
    container_name: vpn_xray
    volumes:
      - ./shared_xray_config:/etc/xray
    ports:
      - "10000:10000"
      - "8443:8443"
    networks:
      - vpn_net

  caddy:
    image: caddy:2.7.6
    container_name: vpn_caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy:/etc/caddy
      - ./caddy:/srv/www
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - vpn_net
    depends_on:
      - xray
      - app

volumes:
  caddy_data:
  caddy_config:

networks:
  vpn_net:
    driver: bridge
