version: '3.8'

services:
  app:
    build: ./app
    # container_name: vpn_app  <-- УДАЛИТЬ
    environment:
      - TELEGRAM_TOKEN=ВАШ_ТЕЛЕГРАМ_ТОКЕН
    volumes:
      - ./xray/config.json:/app/config.json
      - /var/run/docker.sock:/var/run/docker.sock
      - app_data:/app/data
    networks:
      - vpn_net
    restart: always

  xray:
    image: teddysun/xray
    # container_name: vpn_xray <-- УДАЛИТЬ
    volumes:
      - ./xray/config.json:/etc/xray/config.json
    ports:
      - "443:443"
    networks:
      - vpn_net
    restart: always

volumes:
  app_data:

networks:
  vpn_net:
    driver: bridge