version: '3.8'

services:
  app:
    build: ./app
    container_name: vpn_app
    environment:
      # ВАЖНО: Замените на ваш реальный токен!
      - TELEGRAM_TOKEN=7697602760:AAEdu5NLl2UEZYTuyAit3ImiziiVn_vYppE
    volumes:
      # Монтируем конфиг Xray в контейнер app, чтобы его можно было изменять
      - ./xray/config.json:/app/config.json
      # Монтируем Docker Socket, чтобы управлять контейнерами изнутри
      - /var/run/docker.sock:/var/run/docker.sock
      # Создаем volume для хранения файла базы данных
      - app_data:/app/data
    ports:
      - "8000:8000"  # для API
    networks:
      - vpn_net
    restart: always

  xray:
    image: teddysun/xray
    container_name: vpn_xray
    volumes:
      - ./xray/config.json:/etc/xray/config.json
    ports:
      - "10000:10000"
    networks:
      - vpn_net
    restart: always

  caddy:
    image: caddy:2.7.6
    container_name: vpn_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - vpn_net
    restart: always

volumes:
  caddy_data:
  caddy_config:
  app_data: # Объявляем volume для данных приложения

networks:
  vpn_net:
    driver: bridge